version: '3'

services:
  indeed-scrape-api:
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: go run cmd/main.go



# ref: https://www.firehydrant.io/blog/developer-a-go-app-with-docker-compose/